### ISSUE TITLE
Duplicate Definitions

### ISSUE THREAD

**Issue by jelilat** [project3fusion/StarkSharp#1]
There's a lot of duplicate definitions between [~JsonPpcRequest~ JsonRpcRequest](https://github.com/project3fusion/StarkSharp/blob/main/StarkSharp/StarkSharp.Rpc/JsonPpcRequest.cs) and [JsonRpc](https://github.com/project3fusion/StarkSharp/blob/main/StarkSharp/StarkSharp.Rpc/JsonRpc.cs)

**Comment by LastCeri** [comment]
https://github.com/project3fusion/StarkSharp/commit/bd1359e6a27334bae5fc5ac828ffc4e8f70bdf1e
