### ISSUE TITLE
StarkSharp.Base.Net.Hash and StarkSharp.Base.Net.Transaction are missing

### ISSUE THREAD

**Issue by Zeddex** [project3fusion/StarkSharp#12]
namespaces StarkSharp.Base.Net.Hash and StarkSharp.Base.Net.Transaction are missing

**Comment by LastCeri** [comment]
Thank you for your interest. Necessary corrections were made [https://github.com/project3fusion/StarkSharp/commit/ba06f1030819b31ac8fdacbb78be8016acbc4115](url)
