### ISSUE TITLE
Unity JsonRpc request bug

### ISSUE THREAD

**Issue by jelilat** [project3fusion/StarkSharp#2]
According to [this](https://github.com/project3fusion/StarkSharp/blob/main/StarkSharp/StarkSharp.Rpc/RpcPlatform/RequestUnity.cs#L19), [this](https://github.com/project3fusion/StarkSharp/blob/main/StarkSharp/StarkSharp.Rpc/JsonPpcRequest.cs#L77) takes only 1 argument, but you have 2.

**Comment by LastCeri** [comment]
https://github.com/project3fusion/StarkSharp/commit/bd1359e6a27334bae5fc5ac828ffc4e8f70bdf1e

**Comment by LastCeri** [comment]
https://github.com/project3fusion/StarkSharp/commit/bd1359e6a27334bae5fc5ac828ffc4e8f70bdf1e
