### ISSUE TITLE
Contract interaction does not support multiple calldata

### ISSUE THREAD

**Issue by jelilat** [project3fusion/StarkSharp#3]
[This](https://github.com/project3fusion/StarkSharp/blob/main/StarkSharp/StarkSharp.Connector/Components/ContractInteraction/ContractInteraction.cs#L12) does not account for cases where the contract call may have more than 1 calldata. It should be an object instead. 

An example is `get_lp_balance` in [this contract.](https://voyager.online/contract/0x010884171baf1914edc28d7afb619b40a4051cfae78a094a55d230f19e944a28#readContract)

**Comment by LastCeri** [comment]
Fixed; https://github.com/project3fusion/StarkSharp/commit/eb73a55e38354d1e40f603282271c239164b153f
