### ISSUE TITLE
Bugs in Unity Settings

### ISSUE THREAD

**Issue by jelilat** [project3fusion/StarkSharp#4]
1. [These lines](https://github.com/project3fusion/StarkSharp/blob/main/StarkSharp/StarkSharp.Platform/Unity/Components/Editor/StarkSharpSettingsEditorWindow.cs#L159C61-L160C78) should be the following instead
```
// webSocketipadress is duplicated
sw.WriteLine($"        public static string webSocketWebsiteDomain = \"{webSocketWebsiteDomain}\";");
sw.WriteLine($"        public static string webSocketURL = \"{webSocketURL}\";");
```
2. The new settings folder created [here](https://github.com/project3fusion/StarkSharp/blob/main/StarkSharp/StarkSharp.Platform/Unity/Components/Editor/StarkSharpSettingsEditorWindow.cs#L147) is clashing with [this](https://github.com/project3fusion/StarkSharp/tree/main/StarkSharp/StarkSharp.Resources/Settings), causing build errors. You can either delete the initial Settings folder or go with defining them as PlayPrefs.

**Comment by LastCeri** [comment]
https://github.com/project3fusion/StarkSharp/commit/a1c3df2e8cc8e374fbc5a6812dda897e39b1b042

**Comment by jelilat** [comment]
The second point I raised wasn't addressed in the commit

**Comment by LastCeri** [comment]
> Bahsettiğim ikinci nokta taahhütte ele alınmadı

I made the necessary edits
